### ISSUE TITLE
hook up travis

### ISSUE THREAD

**Issue by jgravois** [Esri/geotrigger-js#45]
probably best to use [encrypted](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) variables for the `clientID/secret` in the [config.js](https://github.com/Esri/geotrigger-js/blob/master/spec/config.js.example#L17-L18)

**Comment by kneemer** [comment]
travis is running the tests, now we just need to get the tests passing.

**Comment by jgravois** [comment]
closed via #48 by the endlessly impressive (and modest) @kneemer
