### ISSUE TITLE
tag 1.0.2

### ISSUE THREAD

**Issue by jgravois** [Esri/geotrigger-js#49]
- [x] selectively include minified source 1d74ec3
- [x] update changelog 1d74ec3
- [x] bump `package.json` 2671391979c216c6a00aecc9c578b8179c55cb9e
- [x] publish to github/npm
- [ ] ?

**Comment by ungoldman** [comment]
- [x] add a [release](https://github.com/Esri/geotrigger-js/releases)! Looks like 1.0.2 is missing. :ghost:

**Comment by jgravois** [comment]
saved by the ghost of christmas past.  *again*.

**Comment by jgravois** [comment]
done and done.  thanks for all the help @kneemer!
